apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-helm.fullname" . }}-configmap
  labels:
    {{- include "otel-helm.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Files.Get "configs/config.yaml" | nindent 4 }}
