apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-helm.fullname" . }}
  labels:
    {{- include "otel-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: healthcheck
      port: 13133
      targetPort: 13133
      protocol: TCP
    - name: grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    {{- include "otel-helm.selectorLabels" . | nindent 4 }}
